import type { Metadata } from "next";
import Sidebar from "@/components/layout/sidebar";
import Header from "@/components/layout/header";
import { requireAuth } from "@/lib/auth/requireAuth";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await requireAuth([])
  return (
    <div className="flex min-h-screen">
      <Sidebar />
      <div className="flex-1">
        <Header />
        <main className="p-6">{children}</main>
      </div>
    </div>
  );
}
